train:
    content_dir: "dataset/content/train"
    style_dir: "dataset/style/train"
    sample_output_dir: "out/sample"
    save_dir: "run"
    log_dir: "log"
    vgg_path: "pretrained/vgg_normalised.pth"
    batch_size: 1
    epochs: 2
    lr: 5.0e-4
    d_lr: 5.0e-4
    lr_decay: 1.0e-5
    content_weight: 7
    style_weight: 10
    cls_weight: 5
    bin_weight: 5
    id_1_weight: 50
    id_2_weight: 1
    max_iterations: 160000
    gan_ratio: 0.3
    gr_freq: 1
    num_workers: 4
    num_iterations_per_sample_generation: 1000
